# 10년치 데이터 통합

In [1]:
import pandas as pd
import numpy as np

In [2]:
def df_attribute(attribute_name):
    attribute = pd.read_excel('data/attri/{}.xls'.format(attribute_name) ,skiprows = [0,1,2,3,4])
    attribute['Unnamed: 2'] = attribute['Unnamed: 2'] + attribute['Unnamed: 0']
    attribute.set_index('Unnamed: 2', inplace=True)
    attribute = attribute[['2009/Annual', '2010/Annual', '2011/Annual', '2012/Annual', '2013/Annual','2014/Annual', '2015/Annual', '2016/Annual', '2017/Annual', '2018/Annual','2019/Annual']]
    attribute.columns=['2009', '2010', '2011', '2012', '2013', '2014','2015','2016','2017','2018','2019']
    attribute = pd.DataFrame(attribute.drop('NameKIS').stack(dropna=False))
    attribute.columns=[attribute_name]
    attribute.reset_index(inplace=True)
    attribute.rename(columns = {'Unnamed: 2' : '기업명'}, inplace = True)
    attribute.rename(columns = {'level_1' : '년도'}, inplace = True)
    return attribute


# year/Annual 형식 (kis code 포함)
def df_attribute1(attribute_name):
    attribute = pd.read_excel('data/attri/{}.xls'.format(attribute_name) ,skiprows = [0,1,2,3,4])
    attribute['Unnamed: 2'] = attribute['Unnamed: 2'] + attribute['Unnamed: 0']
    attribute.set_index('Unnamed: 2', inplace=True)
    attribute = attribute[['2009/Annual', '2010/Annual', '2011/Annual', '2012/Annual', '2013/Annual','2014/Annual', '2015/Annual', '2016/Annual', '2017/Annual', '2018/Annual','2019/Annual']]
    attribute.columns=['2009', '2010', '2011', '2012', '2013', '2014','2015','2016','2017','2018','2019']
    attribute = pd.DataFrame(attribute.drop('NameKIS').stack(dropna=False))
    attribute.columns=[attribute_name]
    attribute.reset_index(inplace=True)

    return attribute

# year 형식 (kis code 포함)
def df_attribute2(attribute_name):
    attribute = pd.read_excel('data/attri/{}.xls'.format(attribute_name) ,skiprows = [0,1,2,3,4])
    attribute['Unnamed: 2'] = attribute['Unnamed: 2'] + attribute['Unnamed: 0']
    attribute.set_index('Unnamed: 2', inplace=True)
    attribute = attribute[['2009', '2010', '2011', '2012', '2013', '2014','2015','2016','2017','2018','2019']]
    attribute = pd.DataFrame(attribute.drop('NameKIS').stack(dropna=False))
    attribute.columns=[attribute_name]
    attribute.reset_index(inplace=True)

    return attribute

# 2015-2018 year 형식
def df_attribute3(attribute_name):
    attribute = pd.read_excel('data/attri/{}.xls'.format(attribute_name) ,skiprows = [0,1,2,3,4])
    attribute['Unnamed: 2'] = attribute['Unnamed: 2'] + attribute['Unnamed: 0']
    attribute.set_index('Unnamed: 2', inplace=True)
    attribute = attribute[['2009', '2010', '2011', '2012', '2013', '2014','2015','2016','2017','2018','2019']]
    attribute = pd.DataFrame(attribute.drop('NameKIS').stack(dropna=False))
    attribute.columns=[attribute_name]
    attribute.reset_index(inplace=True)

    return attribute

In [3]:
매출액 = df_attribute('매출액')

당기순이익 = df_attribute1('당기순이익')
매출액영업이익률 = df_attribute1('매출액영업이익률')
매출채권회전율 = df_attribute1('매출채권회전율')
부채비율 = df_attribute1('부채비율')
영업활동현금흐름 = df_attribute1('영업활동현금흐름')
유동비율 = df_attribute1('유동비율')
자기자본순이익률 = df_attribute1('자기자본순이익률')
자산총계 = df_attribute1('자산총계')
재고자산회전율 = df_attribute1('재고자산회전율')
종업원수 = df_attribute1('종업원수')
종업원수증가율 = df_attribute1('종업원수증가율')
영업활동현금흐름이자보상비율 = df_attribute1('영업활동현금흐름이자보상비율')
감가상각율 = df_attribute1('감가상각율')
금융비용_매출액비율 = df_attribute1('금융비용_매출액비율')
오류수정및회계정책변경 = df_attribute1('오류수정및회계정책변경')
유동자산 = df_attribute1('유동자산')
유형자산 = df_attribute1('유형자산')
총자산증가율 = df_attribute1('총자산증가율')
매출액증가율 = df_attribute1('매출액증가율')
판매비와관리비 = df_attribute1('판매비와관리비')
장기매출채권대손충당금 = df_attribute1('장기매출채권대손충당금')
매출채권 = df_attribute1('매출채권')
매출채권대손충당금 = df_attribute1('매출채권대손충당금')
장기매출채권 = df_attribute1('장기매출채권')
ROA = df_attribute1('ROA')

감사법인 = df_attribute2('감사법인')
감사의견 = df_attribute2('감사의견')
# 시장구분
# 업종분류

신용평점 = df_attribute3('신용평점')

In [4]:
data = pd.concat([매출액, 당기순이익, 매출액영업이익률, 매출채권회전율, 부채비율, 
                영업활동현금흐름, 유동비율, 자기자본순이익률, 자산총계, 재고자산회전율, 영업활동현금흐름이자보상비율, 
                종업원수, 종업원수증가율, 감가상각율, 금융비용_매출액비율, 오류수정및회계정책변경, 유동자산, 유형자산, 총자산증가율, 매출액증가율, 판매비와관리비, 장기매출채권대손충당금, 매출채권, 매출채권대손충당금, 장기매출채권, 감사법인, 감사의견, 신용평점], axis = 1)
data

,기업명,년도,매출액,Unnamed: 2,level_1,당기순이익,Unnamed: 2,level_1,매출액영업이익률,Unnamed: 2,...,장기매출채권,Unnamed: 2,level_1,감사법인,Unnamed: 2,level_1,감사의견,Unnamed: 2,level_1,신용평점
0,(주)메타바이오메드000292,2009,22892117000,(주)메타바이오메드000292,2009,2507839000,(주)메타바이오메드000292,2009,20.44,(주)메타바이오메드000292,...,NaN,(주)메타바이오메드000292,2009,안진,(주)메타바이오메드000292,2009,적정,(주)메타바이오메드000292,2009,5
1,(주)메타바이오메드000292,2010,23309340000,(주)메타바이오메드000292,2010,734452000,(주)메타바이오메드000292,2010,14.77,(주)메타바이오메드000292,...,NaN,(주)메타바이오메드000292,2010,안진,(주)메타바이오메드000292,2010,적정,(주)메타바이오메드000292,2010,5
2,(주)메타바이오메드000292,2011,25201037000,(주)메타바이오메드000292,2011,1734508000,(주)메타바이오메드000292,2011,15.94,(주)메타바이오메드000292,...,NaN,(주)메타바이오메드000292,2011,안진,(주)메타바이오메드000292,2011,적정,(주)메타바이오메드000292,2011,4
3,(주)메타바이오메드000292,2012,28956292000,(주)메타바이오메드000292,2012,2384500000,(주)메타바이오메드000292,2012,13.26,(주)메타바이오메드000292,...,NaN,(주)메타바이오메드000292,2012,안진,(주)메타바이오메드000292,2012,적정,(주)메타바이오메드000292,2012,4
4,(주)메타바이오메드000292,2013,33684241000,(주)메타바이오메드000292,2013,2834517000,(주)메타바이오메드000292,2013,11.37,(주)메타바이오메드000292,...,NaN,(주)메타바이오메드000292,2013,안진회계법인,(주)메타바이오메드000292,2013,적정,(주)메타바이오메드000292,2013,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341710,(주)우림공업사Z23508,2015,799825000,(주)우림공업사Z23508,2015,NaN,(주)우림공업사Z23508,2015,5.11,(주)우림공업사Z23508,...,NaN,(주)우림공업사Z23508,2015,NaN,(주)우림공업사Z23508,2015,NaN,(주)우림공업사Z23508,2015,7
341711,(주)우림공업사Z23508,2016,1045628000,(주)우림공업사Z23508,2016,NaN,(주)우림공업사Z23508,2016,5.74,(주)우림공업사Z23508,...,NaN,(주)우림공업사Z23508,2016,NaN,(주)우림공업사Z23508,2016,NaN,(주)우림공업사Z23508,2016,6
341712,(주)우림공업사Z23508,2017,306845000,(주)우림공업사Z23508,2017,NaN,(주)우림공업사Z23508,2017,-28.58,(주)우림공업사Z23508,...,NaN,(주)우림공업사Z23508,2017,NaN,(주)우림공업사Z23508,2017,NaN,(주)우림공업사Z23508,2017,9
341713,(주)우림공업사Z23508,2018,1754355000,(주)우림공업사Z23508,2018,151416000,(주)우림공업사Z23508,2018,17.06,(주)우림공업사Z23508,...,NaN,(주)우림공업사Z23508,2018,NaN,(주)우림공업사Z23508,2018,감사미필,(주)우림공업사Z23508,2018,7
341714,(주)우림공업사Z23508,2019,2330752000,(주)우림공업사Z23508,2019,-1123007000,(주)우림공업사Z23508,2019,-35.58,(주)우림공업사Z23508,...,NaN,(주)우림공업사Z23508,2019,다름공인회계사감사반(제264호),(주)우림공업사Z23508,2019,적정,(주)우림공업사Z23508,2019,9

In [5]:
data.drop(['level_1'], axis = 1, inplace = True)
data.drop(['Unnamed: 2'], axis = 1, inplace = True)
data

,기업명,년도,매출액,당기순이익,매출액영업이익률,매출채권회전율,부채비율,영업활동현금흐름,유동비율,자기자본순이익률,...,총자산증가율,매출액증가율,판매비와관리비,장기매출채권대손충당금,매출채권,매출채권대손충당금,장기매출채권,감사법인,감사의견,신용평점
0,(주)메타바이오메드000292,2009,22892117000,2507839000,20.44,3.48,91.76,3305066000,227.7,12.27,...,35.03,23.01,7173163000,NaN,6278277000,464755000,NaN,안진,적정,5
1,(주)메타바이오메드000292,2010,23309340000,734452000,14.77,3.07,57.45,827272000,293.53,2.79,...,20.31,1.82,8011257000,NaN,7848657000,578414000,NaN,안진,적정,5
2,(주)메타바이오메드000292,2011,25201037000,1734508000,15.94,2.87,30.26,3987995000,153.04,4.87,...,5.64,8.12,7594647000,NaN,8327161000,819148000,NaN,안진,적정,4
3,(주)메타바이오메드000292,2012,28956292000,2384500000,13.26,3.19,68.17,4154058000,93.01,5.82,...,35.83,14.9,7963578000,NaN,8020696000,985455000,NaN,안진,적정,4
4,(주)메타바이오메드000292,2013,33684241000,2834517000,11.37,3.4,85.18,4290916000,111.79,6.41,...,21.82,16.33,9008275000,NaN,9467892000,1330480000,NaN,안진회계법인,적정,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341710,(주)우림공업사Z23508,2015,799825000,NaN,5.11,34.62,8.47,NaN,1555.23,16.88,...,-17.6,-0.75,314821000,NaN,20398000,NaN,NaN,NaN,NaN,7
341711,(주)우림공업사Z23508,2016,1045628000,NaN,5.74,46.01,20.63,NaN,453.02,34.92,...,-44.53,30.73,312115000,NaN,25055000,NaN,NaN,NaN,NaN,6
341712,(주)우림공업사Z23508,2017,306845000,NaN,-28.58,10.53,1643.49,NaN,2.21,-59.55,...,4063.33,-70.65,394539000,NaN,33248000,NaN,NaN,NaN,NaN,9
341713,(주)우림공업사Z23508,2018,1754355000,151416000,17.06,32.85,1558.64,-8476000,49.01,35.01,...,35.45,471.74,372049000,NaN,73562000,NaN,NaN,NaN,감사미필,7
341714,(주)우림공업사Z23508,2019,2330752000,-1123007000,-35.58,31.08,3163.6,-5839000,5.82,-296.46,...,-3.38,32.86,1671503000,NaN,76444000,NaN,NaN,다름공인회계사감사반(제264호),적정,9

In [6]:
ROA.columns = ['기업명', '년도', 'ROA']

In [7]:
data = pd.merge(data, ROA, how = 'left')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341715 entries, 0 to 341714
Data columns (total 31 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   기업명             341715 non-null  object
 1   년도              341715 non-null  object
 2   매출액             258760 non-null  object
 3   당기순이익           218606 non-null  object
 4   매출액영업이익률        258678 non-null  object
 5   매출채권회전율         237151 non-null  object
 6   부채비율            250457 non-null  object
 7   영업활동현금흐름        218606 non-null  object
 8   유동비율            270816 non-null  object
 9   자기자본순이익률        246203 non-null  object
 10  자산총계            271508 non-null  object
 11  재고자산회전율         206529 non-null  object
 12  영업활동현금흐름이자보상비율  192677 non-null  object
 13  종업원수            225440 non-null  object
 14  종업원수증가율         149918 non-null  object
 15  감가상각율           246753 non-null  object
 16  금융비용_매출액비율      225149 non-null  object
 17  오류수정및회계정책변경     8233 non-null    object
 18  유동자산            271483 non-null  object
 19  유형자산            259824 non-null  object
 20  총자산증가율          254210 non-null  object
 21  매출액증가율          242303 non-null  object
 22  판매비와관리비         270747 non-null  object
 23  장기매출채권대손충당금     7300 non-null    object
 24  매출채권            222646 non-null  object
 25  매출채권대손충당금       166096 non-null  object
 26  장기매출채권          9986 non-null    object
 27  감사법인            204330 non-null  object
 28  감사의견            220367 non-null  object
 29  신용평점            270681 non-null  object
 30  ROA             270881 non-null  object
dtypes: object(31)
memory usage: 83.4+ MB

In [9]:
data.감사의견.value_counts()

적정                    192004
감사미필                   16127
한정(감사범위제한)              7447
의견거절(감사범위제한)            1700
한정(기업회계기준위배)            1262
의견거절(계속기업존속의문시)          966
의견거절                     455
한정                       190
부적정(계속기업존속의문시)           130
부적정(기업회계기준위배-회계처리)        72
부적정                       12
의견거절(독립성결여)                2
Name: 감사의견, dtype: int64

## (당기-전기)/전기 함수

In [10]:
def fluctuation_rate1(df):
    변동_at = df.copy()
    변동_at = 변동_at.loc[:, '2009':'2019']
    for idx in range(len(df.columns)-1):
        변동_at[df.columns[idx+1]] =\
        (df[df.columns[idx+1]]-df[df.columns[idx]])/df[df.columns[idx]]
    return 변동_at

## 당기/전기 함수

In [11]:
def fluctuation_rate2(df):
    변동_at = df.copy()
    변동_at = 변동_at.loc[:, '2009':'2019']
    for idx in range(len(df.columns)-1):
        변동_at[df.columns[idx+1]] =\
        df[df.columns[idx+1]]/df[df.columns[idx]]
    return 변동_at

## 당기-전기 함수

In [12]:
def fluctuation_rate3(df):
    변동_at = df.copy()
    변동_at = 변동_at.loc[:, '2009':'2019']
    for idx in range(len(df.columns)-1):
        변동_at[df.columns[idx+1]] =\
        df[df.columns[idx+1]]-df[df.columns[idx]]
    return 변동_at

# 활동성 및 주요왜곡표시 지표
## 매출채권회전율변동

In [13]:
data.매출채권회전율 = pd.to_numeric(data.매출채권회전율)
매출채권회전율_at = data.pivot_table(columns='년도', index = '기업명', values='매출채권회전율', aggfunc='mean', dropna=False)

In [14]:
매출채권회전율_변동_at = fluctuation_rate1(매출채권회전율_at)
매출채권회전율_변동_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,0.476190,NaN,NaN,6.992941,1.131292,-0.451381,-0.706949,-0.469072
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.251670,-0.225979
(유)금강주류784532,35.84,0.166853,-0.122190,-0.130482,0.030388,0.010337,-0.160698,-0.074937,-0.067442,0.426434,-0.227564
(유)기흥모터스113624,23.40,0.158547,-0.167466,-0.046079,0.390618,-0.134269,-0.200617,-0.244691,-0.060064,0.712441,0.430726
(유)남부상사827894,6.78,-0.187316,0.065336,0.458262,-0.323598,-0.131261,-0.075547,0.027957,0.014644,0.008247,-0.071575
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
히타치금속한국(주)041866,3.69,0.094851,0.042079,0.016627,-0.105140,-0.190601,0.154839,0.636872,0.134812,0.066165,-0.101551
히타치하이테크코리아(주)380165,5.12,0.386719,-0.053521,-0.087798,0.314845,-0.052109,-0.091623,-0.034582,-0.083582,0.337134,0.181486
힐중공업(주)E60148,NaN,NaN,NaN,NaN,-0.508663,0.464316,-0.174885,-0.560806,0.447785,-0.274317,NaN
힐티코리아(주)389471,4.52,0.068584,0.078675,0.107486,0.100520,0.182677,0.009321,-0.005277,0.025199,-0.027167,0.013298

## 재고자산회전율변동

In [15]:
data.재고자산회전율 = pd.to_numeric(data.재고자산회전율)
재고자산회전율_at = data.pivot_table(columns='년도', index = '기업명', values='재고자산회전율', aggfunc='mean', dropna=False)
재고자산회전율_변동_at = fluctuation_rate1(재고자산회전율_at)
재고자산회전율_변동_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.862079,-0.187572,2.679380,1.632373
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.507400,-0.040673
(유)금강주류784532,42.93,0.221989,-0.312047,-0.057357,0.148736,0.204964,0.007857,-0.168352,-0.310109,0.150936,-0.096682
(유)기흥모터스113624,5.19,-0.005780,0.162791,0.156667,-0.021614,0.106038,0.169108,0.115034,-0.170582,-0.070197,0.178808
(유)남부상사827894,31.31,-0.060364,0.311693,-0.710806,-0.143369,0.643305,-0.269892,-0.221447,0.162374,0.425819,0.027703
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
히타치금속한국(주)041866,4.64,-0.043103,-0.094595,-0.027363,0.227621,-0.035417,0.328294,0.430894,0.082955,-0.049318,-0.066225
히타치하이테크코리아(주)380165,17.65,0.111615,0.594292,-0.147379,0.208474,0.133106,-0.077492,-0.064411,0.050127,0.163142,-0.441558
힐중공업(주)E60148,NaN,NaN,NaN,NaN,NaN,NaN,-0.595927,-0.734566,-0.037456,0.066063,NaN
힐티코리아(주)389471,7.27,-0.127923,-0.072555,0.022109,0.006656,0.142149,-0.086831,-0.003170,-0.007949,-0.088141,0.079086

## 대손충당금율변동

In [16]:
data.장기매출채권대손충당금 = data.장기매출채권대손충당금.fillna(0)
data.매출채권대손충당금 = data.매출채권대손충당금.fillna(0)
data['대손충당금'] = data.장기매출채권대손충당금 + data.매출채권대손충당금

In [17]:
data.장기매출채권 = data.장기매출채권.fillna(0)
data.매출채권 = data.매출채권.fillna(0)
data['매출채권'] = data.장기매출채권 + data.매출채권

In [18]:
data['대손충당금율'] = data.대손충당금 / data.매출채권

In [19]:
data['대손충당금율'] = data['대손충당금율'].where(np.isfinite(data['대손충당금율']), np.nan)

In [20]:
data.대손충당금율 = pd.to_numeric(data.대손충당금율)
대손충당금율_at = data.pivot_table(columns='년도', index = '기업명', values='대손충당금율', aggfunc='mean', dropna=False)
대손충당금율_변동_at = fluctuation_rate2(대손충당금율_at)
대손충당금율_변동_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.983976,0.798750
(유)금강주류784532,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(유)기흥모터스113624,0.013186,0.896905,0.688436,3.898219,1.296516,1.938960,0.971248,0.545995,1.209236,1.610199,0.420112
(유)남부상사827894,0.009888,0.821398,1.082461,1.136569,1.009295,0.697596,1.372688,1.021330,1.014967,1.003648,0.997779
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
히타치금속한국(주)041866,0.017238,0.771805,0.951623,0.976347,0.834490,1.439756,0.881383,1.134861,0.645624,0.963669,1.302758
히타치하이테크코리아(주)380165,0.010101,0.999997,0.999999,1.000009,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN
힐중공업(주)E60148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf,1.048639,32.278018,NaN
힐티코리아(주)389471,0.460108,0.905740,0.700740,1.236349,0.757197,0.959512,0.729622,0.969011,0.812777,0.865167,1.046623

# 안정성 지표
## 유동비율, 유동비율변동

In [21]:
data.유동비율 = pd.to_numeric(data.유동비율)
유동비율_at = data.pivot_table(columns='년도', index = '기업명', values='유동비율', aggfunc='mean', dropna=False)
유동비율_변동_at = fluctuation_rate2(유동비율_at)
유동비율_변동_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,0.554037,1.849915,1.107321,0.371155,0.988566,0.996101,0.718051,1.170710
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.782303,1.067481
(유)금강주류784532,29.80,1.346980,0.943697,1.024287,1.068299,1.024849,1.451977,1.087062,1.334079,0.960201,1.015368
(유)기흥모터스113624,61.78,1.039657,1.162852,1.150087,1.061816,1.096919,1.158721,1.072371,0.998311,0.938603,1.139669
(유)남부상사827894,218.41,0.717916,1.019005,0.612530,0.471237,1.134649,0.811963,1.382443,0.719271,1.032426,1.324622
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,208.47,1.490862,0.593694,1.527964,0.798113,0.916896,1.053800,0.837135,1.322730,0.748162,1.191372
히타치금속한국(주)041866,154.37,1.139600,0.960834,0.764894,1.516436,1.017138,1.703691,0.812244,0.812908,0.970267,1.076955
히타치하이테크코리아(주)380165,349.04,0.781773,1.051929,1.389249,1.368007,1.104176,0.744318,0.723000,1.113188,0.894219,0.833886
힐중공업(주)E60148,NaN,NaN,NaN,0.941658,2.770531,2.054054,0.233340,0.965894,0.478814,0.130187,NaN
힐티코리아(주)389471,222.54,1.125011,1.184894,0.804349,0.956708,1.116524,0.950683,1.207585,0.942346,1.077972,0.998150

In [22]:
유동비율_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,369.56,204.75,378.77,419.42,155.67,153.89,153.29,110.07,128.86
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,107.19,NaN,NaN,NaN,79.56,62.24,66.44
(유)금강주류784532,29.80,40.14,37.88,38.80,41.45,42.48,61.68,67.05,89.45,85.89,87.21
(유)기흥모터스113624,61.78,64.23,74.69,85.90,91.21,100.05,115.93,124.32,124.11,116.49,132.76
(유)남부상사827894,218.41,156.80,159.78,97.87,46.12,52.33,42.49,58.74,42.25,43.62,57.78
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,208.47,310.80,184.52,281.94,225.02,206.32,217.42,182.01,240.75,180.12,214.59
히타치금속한국(주)041866,154.37,175.92,169.03,129.29,196.06,199.42,339.75,275.96,224.33,217.66,234.41
히타치하이테크코리아(주)380165,349.04,272.87,287.04,398.77,545.52,602.35,448.34,324.15,360.84,322.67,269.07
힐중공업(주)E60148,NaN,NaN,87.93,82.80,229.40,471.20,109.95,106.20,50.85,6.62,NaN
힐티코리아(주)389471,222.54,250.36,296.65,238.61,228.28,254.88,242.31,292.61,275.74,297.24,296.69

## 부채비율, 부채비율변동

In [23]:
data.부채비율 = pd.to_numeric(data.부채비율)
부채비율_at = data.pivot_table(columns='년도', index = '기업명', values='부채비율', aggfunc='mean', dropna=False)
부채비율_변동_at = fluctuation_rate2(부채비율_at)
부채비율_변동_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,2.001353,0.422853,1.097218,2.572719,1.185454,1.421254,2.635691,0.504745
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(유)금강주류784532,634.17,0.782787,1.023528,0.833045,0.853002,0.888353,0.666521,1.005379,1.969013,158.634830,0.046595
(유)기흥모터스113624,809.40,0.876168,0.842492,0.556781,0.744965,0.894318,0.880522,1.058622,0.938042,0.843800,1.163466
(유)남부상사827894,134.81,1.003041,0.959030,4.066934,0.907888,0.857107,1.201048,1.050922,0.854617,0.778225,0.979682
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,72.51,0.525721,1.605981,0.556027,1.632491,1.077020,0.851295,1.380569,0.575917,1.697606,0.891522
히타치금속한국(주)041866,100.07,0.870591,1.040060,1.074385,0.838521,0.680387,0.571840,1.312028,1.394768,1.084652,0.929093
히타치하이테크코리아(주)380165,71.93,0.985959,0.810350,0.713416,0.795854,0.913270,1.551342,1.634437,0.484516,1.153510,1.193228
힐중공업(주)E60148,NaN,NaN,NaN,1.098826,1.019469,1.508112,1.334286,5.814219,0.387161,NaN,NaN
힐티코리아(주)389471,80.22,0.752431,0.837641,1.229430,1.019305,0.824495,1.140123,0.775688,1.179870,0.827921,1.204077

## 영업활동현금흐름이자보상비율

In [24]:
data.영업활동현금흐름이자보상비율 = pd.to_numeric(data.영업활동현금흐름이자보상비율)
영업활동현금흐름이자보상비율_at = data.pivot_table(columns='년도', index = '기업명', values='영업활동현금흐름이자보상비율', aggfunc='mean', dropna=False)

## 금융비용/매출액비율

In [25]:
data.금융비용_매출액비율 = pd.to_numeric(data.금융비용_매출액비율)
금융비용_매출액비율_at = data.pivot_table(columns='년도', index = '기업명', values='금융비용_매출액비율', aggfunc='mean', dropna=False)

## 신용평점

In [26]:
data.신용평점 = pd.to_numeric(data.신용평점)
신용평점_at = data.pivot_table(columns='년도', index = '기업명', values='신용평점', aggfunc='mean', dropna=False)

# 수익성 및성장성 지표
## 자기자본순이익률, 자기자본순이익률변동

In [27]:
data.자기자본순이익률 = pd.to_numeric(data.자기자본순이익률)
자기자본순이익률_at = data.pivot_table(columns='년도', index = '기업명', values='자기자본순이익률', aggfunc='mean', dropna=False)
자기자본순이익률_변동_at = fluctuation_rate2(자기자본순이익률_at)
자기자본순이익률_변동_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,0.957757,0.740577,0.273416,12.596040,1.138657,0.231672,3.529201,1.010976
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(유)금강주류784532,35.93,0.941831,0.711879,0.627646,0.969577,0.791269,0.506897,0.602041,-1.398305,-1.472727,25.067215
(유)기흥모터스113624,31.83,0.697141,0.864804,1.906722,1.006832,0.953312,0.609339,0.578505,1.443457,0.254617,1.538462
(유)남부상사827894,-7.91,-0.762326,0.792703,8.282427,1.142713,0.725685,0.820896,0.808163,0.848944,0.891833,0.820497
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,77.97,0.281903,1.196542,0.777186,0.360078,1.971467,0.443143,1.858476,1.318828,1.994924,0.329835
히타치금속한국(주)041866,5.61,4.418895,0.718031,0.594944,1.759207,0.965110,0.910456,0.902871,0.556834,2.249089,0.532685
히타치하이테크코리아(주)380165,9.59,2.942649,2.205882,0.663293,0.989586,0.359520,0.708645,1.499520,1.004484,3.943878,0.961352
힐중공업(주)E60148,NaN,NaN,NaN,375.400000,1.062866,3.638596,0.670754,-1.394126,0.391573,NaN,NaN
힐티코리아(주)389471,20.12,1.120775,0.884701,0.400000,1.139098,0.816282,1.888140,0.431121,1.349338,1.385276,0.833481

## ROA, ROA변동

In [28]:
data.ROA = pd.to_numeric(data.ROA)
ROA_at = data.pivot_table(columns='년도', index = '기업명', values='ROA', aggfunc='mean', dropna=False)
ROA_변동_at = fluctuation_rate2(ROA_at)
ROA_변동_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,0.831668,0.775459,0.309951,9.852632,0.971688,0.202859,1.967480,1.127410
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.971940,0.825286
(유)금강주류784532,4.43,1.169300,0.770270,0.674185,1.111524,0.882943,0.609848,0.695652,-1.062500,-0.352941,7.261905
(유)기흥모터스113624,3.20,0.812500,0.988462,2.626459,1.417778,1.101358,0.661290,0.589670,1.450122,0.273490,1.546012
(유)남부상사827894,-3.29,-0.781155,0.801556,4.106796,0.894799,0.804491,0.794745,0.741736,0.891365,1.053125,0.910979
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,39.67,0.360978,1.214385,0.802760,0.363181,1.812623,0.450490,1.789855,1.379217,1.961840,0.313217
히타치금속한국(주)041866,2.71,4.745387,0.732504,0.578556,1.811009,1.087133,1.095993,0.918367,0.508333,2.098361,0.532118
히타치하이테크코리아(주)380165,5.14,3.204280,2.329083,0.727059,1.076013,0.373209,0.679464,1.270696,1.046536,4.357708,0.925850
힐중공업(주)E60148,NaN,NaN,NaN,444.000000,1.033784,3.049020,0.543051,-0.708553,0.294336,12.388013,NaN
힐티코리아(주)389471,11.06,1.205244,0.965491,0.397824,1.089844,0.844086,1.904459,0.441472,1.368687,1.392989,0.831788

## 적자여부

In [29]:
data.감사의견.value_counts()

적정                    192004
감사미필                   16127
한정(감사범위제한)              7447
의견거절(감사범위제한)            1700
한정(기업회계기준위배)            1262
의견거절(계속기업존속의문시)          966
의견거절                     455
한정                       190
부적정(계속기업존속의문시)           130
부적정(기업회계기준위배-회계처리)        72
부적정                       12
의견거절(독립성결여)                2
Name: 감사의견, dtype: int64

In [30]:
data[data.당기순이익.isnull()].감사의견.value_counts()

의견거절(감사범위제한)       1085
감사미필                934
적정                  211
의견거절                 53
의견거절(계속기업존속의문시)      30
한정(감사범위제한)            8
의견거절(독립성결여)           1
한정                    1
Name: 감사의견, dtype: int64

In [31]:
당기순이익.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341715 entries, 0 to 341714
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 2  341715 non-null  object
 1   level_1     341715 non-null  object
 2   당기순이익       218606 non-null  object
dtypes: object(3)
memory usage: 7.8+ MB

In [32]:
data['적자여부'] = data.당기순이익.apply(lambda x: 0 if x > 0 else 1)

In [33]:
data.적자여부

0         0
1         0
2         0
3         0
4         0
         ..
341710    1
341711    1
341712    1
341713    0
341714    1
Name: 적자여부, Length: 341715, dtype: int64

In [34]:
#data.적자여부 = pd.to_numeric(data.적자여부)
적자여부_at = data.pivot_table(columns='년도', index = '기업명', values='적자여부', aggfunc='mean', dropna=False)

In [35]:
적자여부_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,1,1,1,1,1,1,1,1,1,0,0
(유)그랜드유니버셜트레이딩코리아I83725,1,1,1,1,1,1,1,1,1,1,1
(유)금강주류784532,1,1,1,1,1,1,1,1,1,0,0
(유)기흥모터스113624,0,0,0,0,0,0,0,0,0,0,0
(유)남부상사827894,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,0,0,0,0,0,0,0,0,0,0,0
히타치금속한국(주)041866,0,0,0,0,0,0,0,0,0,0,0
히타치하이테크코리아(주)380165,0,0,0,0,0,0,0,0,0,0,0
힐중공업(주)E60148,1,1,1,1,1,1,1,1,1,1,1
힐티코리아(주)389471,0,0,0,0,0,0,0,0,0,0,0

## 매출액증가율

In [36]:
data.매출액증가율 = pd.to_numeric(data.매출액증가율)
매출액증가율_at = data.pivot_table(columns='년도', index = '기업명', values='매출액증가율', aggfunc='mean', dropna=False)

## 자산퀄리티, 자산퀄리티변동

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341715 entries, 0 to 341714
Data columns (total 34 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   기업명             341715 non-null  object
 1   년도              341715 non-null  object
 2   매출액             258760 non-null  object
 3   당기순이익           218606 non-null  object
 4   매출액영업이익률        258678 non-null  object
 5   매출채권회전율         237151 non-null  float64
 6   부채비율            250457 non-null  float64
 7   영업활동현금흐름        218606 non-null  object
 8   유동비율            270816 non-null  float64
 9   자기자본순이익률        246203 non-null  float64
 10  자산총계            271508 non-null  object
 11  재고자산회전율         206529 non-null  float64
 12  영업활동현금흐름이자보상비율  192677 non-null  float64
 13  종업원수            225440 non-null  object
 14  종업원수증가율         149918 non-null  object
 15  감가상각율           246753 non-null  object
 16  금융비용_매출액비율      225149 non-null  float64
 17  오류수정및회계정책변경     8233 non-null    object
 18  유동자산            271483 non-null  object
 19  유형자산            259824 non-null  object
 20  총자산증가율          254210 non-null  object
 21  매출액증가율          242303 non-null  float64
 22  판매비와관리비         270747 non-null  object
 23  장기매출채권대손충당금     341715 non-null  int64
 24  매출채권            341715 non-null  int64
 25  매출채권대손충당금       341715 non-null  int64
 26  장기매출채권          341715 non-null  int64
 27  감사법인            204330 non-null  object
 28  감사의견            220367 non-null  object
 29  신용평점            270681 non-null  float64
 30  ROA             270881 non-null  float64
 31  대손충당금           341715 non-null  int64
 32  대손충당금율          222825 non-null  float64
 33  적자여부            341715 non-null  int64
dtypes: float64(11), int64(6), object(17)
memory usage: 91.2+ MB

In [38]:
data.유동자산 = pd.to_numeric(data.유동자산)
유동자산_at = data.pivot_table(columns='년도', index = '기업명', values='유동자산', aggfunc='mean', dropna=False)
data.유형자산 = pd.to_numeric(data.유형자산)
유형자산_at = data.pivot_table(columns='년도', index = '기업명', values='유형자산', aggfunc='mean', dropna=False)
data.자산총계 = pd.to_numeric(data.자산총계)
자산총계_at = data.pivot_table(columns='년도', index = '기업명', values='자산총계', aggfunc='mean', dropna=False)
자산퀄리티_at = (1-(유동자산_at+유형자산_at)/자산총계_at)
자산퀄리티_변동_at = fluctuation_rate2(자산퀄리티_at)

## 감가상각율변동

In [39]:
data.감가상각율 = pd.to_numeric(data.감가상각율)
감가상각율_at = data.pivot_table(columns='년도', index = '기업명', values='감가상각율', aggfunc='mean', dropna=False)
감가상각율_변동_at = fluctuation_rate2(감가상각율_at)

## 판관비율, 판관비율변동

In [40]:
data.판매비와관리비 = pd.to_numeric(data.판매비와관리비)
판매비와관리비_at = data.pivot_table(columns='년도', index = '기업명', values='판매비와관리비', aggfunc='mean', dropna=False)

data.매출액 = pd.to_numeric(data.매출액)
매출액_at = data.pivot_table(columns='년도', index = '기업명', values='매출액', aggfunc='mean', dropna=False)
판관비율_at = 판매비와관리비_at/매출액_at
판관비율_변동_at = fluctuation_rate2(판관비율_at)

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341715 entries, 0 to 341714
Data columns (total 34 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   기업명             341715 non-null  object
 1   년도              341715 non-null  object
 2   매출액             258760 non-null  float64
 3   당기순이익           218606 non-null  object
 4   매출액영업이익률        258678 non-null  object
 5   매출채권회전율         237151 non-null  float64
 6   부채비율            250457 non-null  float64
 7   영업활동현금흐름        218606 non-null  object
 8   유동비율            270816 non-null  float64
 9   자기자본순이익률        246203 non-null  float64
 10  자산총계            271508 non-null  float64
 11  재고자산회전율         206529 non-null  float64
 12  영업활동현금흐름이자보상비율  192677 non-null  float64
 13  종업원수            225440 non-null  object
 14  종업원수증가율         149918 non-null  object
 15  감가상각율           246753 non-null  float64
 16  금융비용_매출액비율      225149 non-null  float64
 17  오류수정및회계정책변경     8233 non-null    object
 18  유동자산            271483 non-null  float64
 19  유형자산            259824 non-null  float64
 20  총자산증가율          254210 non-null  object
 21  매출액증가율          242303 non-null  float64
 22  판매비와관리비         270747 non-null  float64
 23  장기매출채권대손충당금     341715 non-null  int64
 24  매출채권            341715 non-null  int64
 25  매출채권대손충당금       341715 non-null  int64
 26  장기매출채권          341715 non-null  int64
 27  감사법인            204330 non-null  object
 28  감사의견            220367 non-null  object
 29  신용평점            270681 non-null  float64
 30  ROA             270881 non-null  float64
 31  대손충당금           341715 non-null  int64
 32  대손충당금율          222825 non-null  float64
 33  적자여부            341715 non-null  int64
dtypes: float64(17), int64(6), object(11)
memory usage: 91.2+ MB

## 총발생액비율, 총발생액비율 변동

In [42]:
data.당기순이익 = pd.to_numeric(data.당기순이익)
당기순이익_at = data.pivot_table(columns='년도', index = '기업명', values='당기순이익', aggfunc='mean', dropna=False)
data.영업활동현금흐름 = pd.to_numeric(data.영업활동현금흐름)
영업활동현금흐름_at = data.pivot_table(columns='년도', index = '기업명', values='영업활동현금흐름', aggfunc='mean', dropna=False)
총발생액비율_at = (당기순이익_at - 영업활동현금흐름_at) / 자산총계_at

In [43]:
순이익변동_at = fluctuation_rate3(당기순이익_at)
영업활동현금흐름변동_at = fluctuation_rate3(영업활동현금흐름_at) ## 변동이 당-전 or 당/전?
총발생액비율_변동_at = (순이익변동_at - 영업활동현금흐름변동_at) / 자산총계_at

## 매영차

In [44]:
data['매영차'] = abs(data.매출액영업이익률 - (data.영업활동현금흐름 / data.매출액))

In [45]:
data.매영차 = pd.to_numeric(data.매영차)
매영차_at = data.pivot_table(columns='년도', index = '기업명', values='매영차', aggfunc='mean', dropna=False)

## 총종차, 매종차

In [46]:
data.종업원수 = pd.to_numeric(data.종업원수)
종업원수_at = data.pivot_table(columns='년도', index = '기업명', values='종업원수', aggfunc='mean', dropna=False)
종업원수_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,2.0,2.0,6.0,8.0,NaN,11.0,20.0,21.0
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,14.0
(유)금강주류784532,25.0,25.0,28.0,28.0,NaN,NaN,25.0,21.0,34.0,53.0,55.0
(유)기흥모터스113624,118.0,118.0,121.0,121.0,140.0,159.0,NaN,NaN,NaN,NaN,201.0
(유)남부상사827894,23.0,23.0,23.0,23.0,NaN,24.0,NaN,NaN,15.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,25.0,30.0,42.0,42.0,60.0,NaN,NaN,NaN,93.0,108.0,120.0
히타치금속한국(주)041866,43.0,43.0,49.0,55.0,55.0,59.0,67.0,123.0,119.0,123.0,117.0
히타치하이테크코리아(주)380165,173.0,173.0,173.0,150.0,147.0,156.0,160.0,155.0,162.0,185.0,224.0
힐중공업(주)E60148,NaN,NaN,NaN,13.0,19.0,21.0,NaN,20.0,14.0,5.0,NaN
힐티코리아(주)389471,147.0,150.0,149.0,146.0,149.0,159.0,182.0,194.0,221.0,243.0,245.0

In [47]:
data.종업원수증가율 = pd.to_numeric(data.종업원수증가율)
종업원수증가율_at = data.pivot_table(columns='년도', index = '기업명', values='종업원수증가율', aggfunc='mean', dropna=False)
종업원수증가율_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,NaN,NaN,200.00,33.33,NaN,NaN,81.82,5.00
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(유)금강주류784532,NaN,NaN,12.00,NaN,NaN,NaN,NaN,-16.00,61.90,55.88,3.77
(유)기흥모터스113624,NaN,NaN,2.54,NaN,15.70,13.57,NaN,NaN,NaN,NaN,NaN
(유)남부상사827894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,-3.85,20.00,40.00,NaN,42.86,NaN,NaN,NaN,NaN,16.13,11.11
히타치금속한국(주)041866,2.38,NaN,13.95,12.24,NaN,7.27,13.56,83.58,-3.25,3.36,-4.88
히타치하이테크코리아(주)380165,6.13,NaN,NaN,-13.29,-2.00,6.12,2.56,-3.13,4.52,14.20,21.08
힐중공업(주)E60148,NaN,NaN,NaN,NaN,46.15,10.53,NaN,NaN,-30.00,-64.29,NaN
힐티코리아(주)389471,-4.55,2.04,-0.67,-2.01,2.05,6.71,14.47,6.59,13.92,9.95,0.82

In [48]:
종업원수[종업원수.columns[0]]

0         (주)메타바이오메드000292
1         (주)메타바이오메드000292
2         (주)메타바이오메드000292
3         (주)메타바이오메드000292
4         (주)메타바이오메드000292
                ...
341710      (주)우림공업사Z23508
341711      (주)우림공업사Z23508
341712      (주)우림공업사Z23508
341713      (주)우림공업사Z23508
341714      (주)우림공업사Z23508
Name: Unnamed: 2, Length: 341715, dtype: object

In [49]:
for idx in range(len(종업원수_at.columns)-1):
    종업원수증가율_at[종업원수_at.columns[idx+1]][종업원수_at[종업원수_at.columns[idx+1]]-종업원수_at[종업원수_at.columns[idx]]==0] = 0

In [50]:
종업원수증가율_at

년도,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
기업명,,,,,,,,,,,
(유)건향개발I57907,NaN,NaN,NaN,NaN,0.00,200.00,33.33,NaN,NaN,81.82,5.00
(유)그랜드유니버셜트레이딩코리아I83725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(유)금강주류784532,NaN,0.00,12.00,0.00,NaN,NaN,NaN,-16.00,61.90,55.88,3.77
(유)기흥모터스113624,NaN,0.00,2.54,0.00,15.70,13.57,NaN,NaN,NaN,NaN,NaN
(유)남부상사827894,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,-3.85,20.00,40.00,0.00,42.86,NaN,NaN,NaN,NaN,16.13,11.11
히타치금속한국(주)041866,2.38,0.00,13.95,12.24,0.00,7.27,13.56,83.58,-3.25,3.36,-4.88
히타치하이테크코리아(주)380165,6.13,0.00,0.00,-13.29,-2.00,6.12,2.56,-3.13,4.52,14.20,21.08
힐중공업(주)E60148,NaN,NaN,NaN,NaN,46.15,10.53,NaN,NaN,-30.00,-64.29,NaN
힐티코리아(주)389471,-4.55,2.04,-0.67,-2.01,2.05,6.71,14.47,6.59,13.92,9.95,0.82

In [51]:
data.총자산증가율 = pd.to_numeric(data.총자산증가율)
총자산증가율_at = data.pivot_table(columns='년도', index = '기업명', values='총자산증가율', aggfunc='mean', dropna=False)
총종차_at = abs(총자산증가율_at - 종업원수증가율_at)
매종차_at = abs(매출액증가율_at - 종업원수증가율_at) ## 매출액인지 매출액증가율인지

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341715 entries, 0 to 341714
Data columns (total 35 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   기업명             341715 non-null  object
 1   년도              341715 non-null  object
 2   매출액             258760 non-null  float64
 3   당기순이익           218606 non-null  float64
 4   매출액영업이익률        258678 non-null  object
 5   매출채권회전율         237151 non-null  float64
 6   부채비율            250457 non-null  float64
 7   영업활동현금흐름        218606 non-null  float64
 8   유동비율            270816 non-null  float64
 9   자기자본순이익률        246203 non-null  float64
 10  자산총계            271508 non-null  float64
 11  재고자산회전율         206529 non-null  float64
 12  영업활동현금흐름이자보상비율  192677 non-null  float64
 13  종업원수            225440 non-null  float64
 14  종업원수증가율         149918 non-null  float64
 15  감가상각율           246753 non-null  float64
 16  금융비용_매출액비율      225149 non-null  float64
 17  오류수정및회계정책변경     8233 non-null    object
 18  유동자산            271483 non-null  float64
 19  유형자산            259824 non-null  float64
 20  총자산증가율          254210 non-null  float64
 21  매출액증가율          242303 non-null  float64
 22  판매비와관리비         270747 non-null  float64
 23  장기매출채권대손충당금     341715 non-null  int64
 24  매출채권            341715 non-null  int64
 25  매출채권대손충당금       341715 non-null  int64
 26  장기매출채권          341715 non-null  int64
 27  감사법인            204330 non-null  object
 28  감사의견            220367 non-null  object
 29  신용평점            270681 non-null  float64
 30  ROA             270881 non-null  float64
 31  대손충당금           341715 non-null  int64
 32  대손충당금율          222825 non-null  float64
 33  적자여부            341715 non-null  int64
 34  매영차             209795 non-null  float64
dtypes: float64(23), int64(6), object(6)
memory usage: 93.9+ MB

## 오류수정및회계정책변경

## 자산총계

In [53]:
data.자산총계 = pd.to_numeric(data.자산총계)

In [54]:
data.자산총계 = np.log(data.자산총계)

In [55]:
data.자산총계 = pd.to_numeric(data.자산총계)
자산총계_at = data.pivot_table(columns='년도', index = '기업명', values='자산총계', aggfunc='mean', dropna=False)

## 상장구분(비상장, 상장, 상장관리)

In [56]:
시장구분 = pd.read_excel('data/attri2/시장구분.xls', skiprows=[0,1,2,3,4,5])
시장구분['Name'] = 시장구분['Name'] + 시장구분['KIS']
시장구분 = 시장구분[['Name', '소속/시장구분/0A0002']]
시장구분.columns = ['Name', '시장구분']

In [57]:
시장구분

                      Name   시장구분
0         (주)메타바이오메드000292  코스닥상장
1              (주)코라000366     외감
2           (주)이건홀딩스000442  코스닥상장
3            동성인쇄(주)000469     외감
4            (주)경기색소000531     외감
...                    ...    ...
31060        (주)인터코스X02373    코넥스
31061        (주)에스엘씨X57312     외감
31062  농업회사법인한국양계(주)X91216     외감
31063  (주)메디라인액티브코리아Y32604     외감
31064       (주)우림공업사Z23508     외감

[31065 rows x 2 columns]

In [58]:
data = pd.merge(data, 시장구분, how = 'left', left_on = '기업명', right_on = 'Name')
data = data.drop('Name', axis = 1)

In [59]:
data.시장구분.value_counts()

외감       315051
코스닥상장     14399
상장         9515
코넥스        1584
코스닥관리      1067
상장관리         99
Name: 시장구분, dtype: int64

In [60]:
# 비상장(0), 상장(1), 상장관리(2) 
data.시장구분 = data.시장구분.map({
    '외감': 0,
    '코스닥상장': 1,
    '상장': 1,
    '코넥스': 1, 
    '코스닥관리': 2,
    '상장관리': 2
})

In [61]:
# LabelBinarizer로도 one-hot encoding 가능
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
a = pd.DataFrame(lb.fit_transform(data.시장구분))
data = pd.concat([data,a],axis=1)

In [62]:
data.columns =[           '기업명',             '년도',            '매출액',          '당기순이익',
             '매출액영업이익률',        '매출채권회전율',           '부채비율',       '영업활동현금흐름',
                 '유동비율',       '자기자본순이익률',           '자산총계',        '재고자산회전율',
       '영업활동현금흐름이자보상비율',           '종업원수',        '종업원수증가율',          '감가상각율',
           '금융비용_매출액비율',    '오류수정및회계정책변경',           '유동자산',           '유형자산',
               '총자산증가율',         '매출액증가율',        '판매비와관리비',    '장기매출채권대손충당금',
                 '매출채권',      '매출채권대손충당금',         '장기매출채권',           '감사법인',
                 '감사의견',           '신용평점',            'ROA',          '대손충당금',
               '대손충당금율',           '적자여부',            '매영차',           '시장구분',               '비상장',                '상장',
                      '상장관리']

## 빅4여부

In [63]:
big4 = ['삼일', '삼일회계법인', '삼정', '삼정회계법인', '안진', '안진회계법인', '한영', '한영회계법인']

In [64]:
data.감사법인.value_counts()

삼일회계법인               10291
대주회계법인                6983
삼정회계법인                6791
삼덕회계법인                6525
안진회계법인                5845
                     ...
창석공인회계감사반(제485호)         1
알천공인회계감사반(제51호)          1
인의공인회계사감사반(제388호)        1
한율회계법인                   1
제494호                    1
Name: 감사법인, Length: 1289, dtype: int64

In [65]:
data['빅4여부'] = data.감사법인.apply(lambda x: 1 if x in big4 else 0)

## 감사법인변경여부

In [66]:
감사법인 = df_attribute2('감사법인')
감사법인_변동_df = 감사법인.set_index(['Unnamed: 2','level_1']).unstack(1)
감사법인_변동_df = 감사법인_변동_df.fillna(0)

In [67]:
감사법인_변동_여부_df = 감사법인_변동_df.copy()

In [68]:
감사법인_변동_여부_df

                        감사법인                                               \
level_1                 2009 2010    2011    2012    2013    2014    2015
Unnamed: 2
(유)건향개발I57907              0    0       0       0       0       0       0
(유)그랜드유니버셜트레이딩코리아I83725    0    0       0       0       0       0       0
(유)금강주류784532              0    0       0       0       0       0       0
(유)기흥모터스113624            다산   다산      다산  다산회계법인  다산회계법인  다산회계법인  다산회계법인
(유)남부상사827894              0    0       0       0       0       0       0
...                      ...  ...     ...     ...     ...     ...     ...
히스보험중개(주)197675            0   대주  대주회계법인  대주회계법인  대주회계법인  대주회계법인  대주회계법인
히타치금속한국(주)041866          한영   한영      한영      한영  한영회계법인  한영회계법인  한영회계법인
히타치하이테크코리아(주)380165       한영   한영      한영      한영  한영회계법인  한영회계법인  한영회계법인
힐중공업(주)E60148              0    0       0       0       0       0       0
힐티코리아(주)389471            삼일   삼일      삼일      삼일  삼일회계법인  삼일회계법인  삼일회계법인


level_1                    2016    2017      2018                2019
Unnamed: 2
(유)건향개발I57907                 0       0  이정지율회계법인            이정지율회계법인
(유)그랜드유니버셜트레이딩코리아I83725       0       0         0                   0
(유)금강주류784532                 0       0         0  도우리공인회계사감사반(제459호)
(유)기흥모터스113624           다산회계법인  다산회계법인    다산회계법인              다산회계법인
(유)남부상사827894                 0       0         0                   0
...                         ...     ...       ...                 ...
히스보험중개(주)197675          대주회계법인  대주회계법인    대주회계법인              대주회계법인
히타치금속한국(주)041866         한영회계법인  한영회계법인    한영회계법인              한영회계법인
히타치하이테크코리아(주)380165      한영회계법인  한영회계법인    한영회계법인              한영회계법인
힐중공업(주)E60148                 0  삼영회계법인    삼영회계법인              성운회계법인
힐티코리아(주)389471           삼일회계법인  삼일회계법인    삼일회계법인              삼일회계법인

[31065 rows x 11 columns]

In [69]:
import tqdm

In [70]:
for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][0] != 감사법인_변동_df.loc[firm][1]:
        감사법인_변동_여부_df[('감사법인', '2010')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2010')][firm] = 0
        
for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][1] != 감사법인_변동_df.loc[firm][2]:
        감사법인_변동_여부_df[('감사법인', '2011')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2011')][firm] = 0
        
for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][2] != 감사법인_변동_df.loc[firm][3]:
        감사법인_변동_여부_df[('감사법인', '2012')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2012')][firm] = 0
        
for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][3] != 감사법인_변동_df.loc[firm][4]:
        감사법인_변동_여부_df[('감사법인', '2013')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2013')][firm] = 0
        
for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][4] != 감사법인_변동_df.loc[firm][5]:
        감사법인_변동_여부_df[('감사법인', '2014')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2014')][firm] = 0

for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][5] != 감사법인_변동_df.loc[firm][6]:
        감사법인_변동_여부_df[('감사법인', '2015')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2015')][firm] = 0
        
for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][6] != 감사법인_변동_df.loc[firm][7]:
        감사법인_변동_여부_df[('감사법인', '2016')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2016')][firm] = 0
        
for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][7] != 감사법인_변동_df.loc[firm][8]:
        감사법인_변동_여부_df[('감사법인', '2017')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2017')][firm] = 0
        
for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][8] != 감사법인_변동_df.loc[firm][9]:
        감사법인_변동_여부_df[('감사법인', '2018')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2018')][firm] = 0
        
for firm in tqdm.tqdm(감사법인_변동_df.index):
    if 감사법인_변동_df.loc[firm][9] != 감사법인_변동_df.loc[firm][10]:
        감사법인_변동_여부_df[('감사법인', '2019')][firm] = 1
    else:
        감사법인_변동_여부_df[('감사법인', '2019')][firm] = 0

100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:14<00:00, 2118.63it/s]
100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:14<00:00, 2137.23it/s]
100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:14<00:00, 2072.67it/s]
100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:16<00:00, 1874.81it/s]
100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:14<00:00, 2160.06it/s]
100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:14<00:00, 2162.01it/s]
100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:14<00:00, 2176.05it/s]
100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:14<00:00, 2186.90it/s]
100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:14<00:00, 2190.13it/s]
100%|██████████████████████████████████████████████████████████████████████████| 31065/31065 [00:14<00:00, 2201.43it/s]

# 데이터 통합

In [71]:
매출채권회전율_변동_at=매출채권회전율_변동_at.stack(dropna=False,).reset_index()
매출채권회전율_변동_at.columns = ['기업명', '년도', '매출채권회전율변동']

재고자산회전율_변동_at=재고자산회전율_변동_at.stack(dropna=False).reset_index()
재고자산회전율_변동_at.columns = ['기업명', '년도', '재고자산회전율변동']

대손충당금율_변동_at=대손충당금율_변동_at.stack(dropna=False).reset_index()
대손충당금율_변동_at.columns = ['기업명', '년도', '대손충당금율변동']

In [72]:
유동비율_at=유동비율_at.stack(dropna=False).reset_index()
유동비율_at.columns = ['기업명', '년도', '유동비율']

유동비율_변동_at=유동비율_변동_at.stack(dropna=False).reset_index()
유동비율_변동_at.columns = ['기업명', '년도', '유동비율변동']

부채비율_at=부채비율_at.stack(dropna=False).reset_index()
부채비율_at.columns = ['기업명', '년도', '부채비율']

부채비율_변동_at=부채비율_변동_at.stack(dropna=False).reset_index()
부채비율_변동_at.columns = ['기업명', '년도', '부채비율변동']

영업활동현금흐름이자보상비율_at=영업활동현금흐름이자보상비율_at.stack(dropna=False).reset_index()
영업활동현금흐름이자보상비율_at.columns = ['기업명', '년도', '영업활동현금흐름이자보상비율']

금융비용_매출액비율_at=금융비용_매출액비율_at.stack(dropna=False).reset_index()
금융비용_매출액비율_at.columns = ['기업명', '년도', '금융비용_매출액비율']

신용평점_at=신용평점_at.stack(dropna=False).reset_index()
신용평점_at.columns = ['기업명', '년도', '신용평점']

In [73]:
자기자본순이익률_at=자기자본순이익률_at.stack(dropna=False).reset_index()
자기자본순이익률_at.columns = ['기업명', '년도', '자기자본순이익률']

자기자본순이익률_변동_at=자기자본순이익률_변동_at.stack(dropna=False).reset_index()
자기자본순이익률_변동_at.columns = ['기업명', '년도', '자기자본순이익률변동']

ROA_at=ROA_at.stack(dropna=False).reset_index()
ROA_at.columns = ['기업명', '년도', 'ROA']

ROA_변동_at=ROA_변동_at.stack(dropna=False).reset_index()
ROA_변동_at.columns = ['기업명', '년도', 'ROA변동']

적자여부_at=적자여부_at.stack(dropna=False).reset_index() # 123
적자여부_at.columns = ['기업명', '년도', '적자여부']

매출액증가율_at=매출액증가율_at.stack(dropna=False).reset_index() 
매출액증가율_at.columns = ['기업명', '년도', '매출액증가율']

In [74]:
자산퀄리티_at=자산퀄리티_at.stack(dropna=False).reset_index() 
자산퀄리티_at.columns = ['기업명', '년도', '자산퀄리티']

자산퀄리티_변동_at=자산퀄리티_변동_at.stack(dropna=False).reset_index() 
자산퀄리티_변동_at.columns = ['기업명', '년도', '자산퀄리티변동']

감가상각율_변동_at=감가상각율_변동_at.stack(dropna=False).reset_index() 
감가상각율_변동_at.columns = ['기업명', '년도', '감가상각율변동']

판관비율_at=판관비율_at.stack(dropna=False).reset_index() 
판관비율_at.columns = ['기업명', '년도', '판관비율']

판관비율_변동_at=판관비율_변동_at.stack(dropna=False).reset_index() 
판관비율_변동_at.columns = ['기업명', '년도', '판관비율변동']

총발생액비율_at=총발생액비율_at.stack(dropna=False).reset_index() 
총발생액비율_at.columns = ['기업명', '년도', '총발생액비율']

총발생액비율_변동_at=총발생액비율_변동_at.stack(dropna=False).reset_index() 
총발생액비율_변동_at.columns = ['기업명', '년도', '총발생액비율변동']

매영차_at=매영차_at.stack(dropna=False).reset_index()
매영차_at.columns = ['기업명', '년도', '매영차']

총종차_at=총종차_at.stack(dropna=False).reset_index()
총종차_at.columns = ['기업명', '년도', '총종차']

매종차_at=매종차_at.stack(dropna=False).reset_index()
매종차_at.columns = ['기업명', '년도', '매종차'] 

오류수정및회계정책변경 = pd.read_excel('data/attri2/오류수정및회계정책변경all.xlsx')
오류수정및회계정책변경.drop('Unnamed: 0',axis=1,inplace=True)
오류수정및회계정책변경.년도=오류수정및회계정책변경.년도.astype(str)

In [75]:
자산총계_at=자산총계_at.stack(dropna=False).reset_index()
자산총계_at.columns = ['기업명', '년도', '자산총계']

시장구분_df = data[['기업명','년도','비상장','상장','상장관리']]

In [76]:
빅4여부_df = data[['기업명','년도','빅4여부']]

감사법인_변동_여부_df=감사법인_변동_여부_df.stack(dropna=False).reset_index()
감사법인_변동_여부_df.columns = ['기업명', '년도', '감사법인변동여부']

In [77]:
감사의견_df = data[['기업명','년도','감사의견']]

In [78]:
columns = [매출채권회전율_변동_at,재고자산회전율_변동_at,대손충당금율_변동_at,유동비율_at, 유동비율_변동_at,부채비율_at,
           부채비율_변동_at, 영업활동현금흐름이자보상비율_at,금융비용_매출액비율_at,신용평점_at,자기자본순이익률_at,
           자기자본순이익률_변동_at, ROA_at, ROA_변동_at,적자여부_at,매출액증가율_at,자산퀄리티_at, 자산퀄리티_변동_at,
           감가상각율_변동_at,판관비율_at, 판관비율_변동_at,총발생액비율_at, 총발생액비율_변동_at,매영차_at,총종차_at,
           매종차_at,오류수정및회계정책변경,자산총계_at,시장구분_df,빅4여부_df, 감사법인_변동_여부_df, 감사의견_df]

In [79]:
from functools import reduce

In [80]:
df_merged = reduce(lambda left, right: pd.merge(left, right, how='inner'), columns)

In [81]:
df_merged

,기업명,년도,매출채권회전율변동,재고자산회전율변동,대손충당금율변동,유동비율,유동비율변동,부채비율,부채비율변동,영업활동현금흐름이자보상비율,...,총종차,매종차,오류수정및회계정책변경여부,자산총계,비상장,상장,상장관리,빅4여부,감사법인변동여부,감사의견
0,(유)건향개발I57907,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,1,0,0,0,0,NaN
1,(유)건향개발I57907,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,1,0,0,0,0,NaN
2,(유)건향개발I57907,2011,NaN,NaN,NaN,369.56,NaN,36.95,NaN,NaN,...,NaN,NaN,1,19.992317,1,0,0,0,0,NaN
3,(유)건향개발I57907,2012,0.476190,NaN,NaN,204.75,0.554037,73.95,2.001353,NaN,...,NaN,NaN,0,20.482245,1,0,0,0,0,NaN
4,(유)건향개발I57907,2013,NaN,NaN,NaN,378.77,1.849915,31.27,0.422853,NaN,...,9.18,35.37,0,20.385970,1,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341710,힐티코리아(주)389471,2015,0.009321,-0.086831,0.729622,242.31,0.950683,59.56,1.140123,NaN,...,6.13,6.06,0,24.284504,1,0,0,1,0,적정
341711,힐티코리아(주)389471,2016,-0.005277,-0.003170,0.969011,292.61,1.207585,46.20,0.775688,NaN,...,9.26,6.80,0,24.257440,1,0,0,1,0,적정
341712,힐티코리아(주)389471,2017,0.025199,-0.007949,0.812777,275.74,0.942346,54.51,1.179870,NaN,...,0.74,1.49,0,24.394284,1,0,0,1,0,적정
341713,힐티코리아(주)389471,2018,-0.027167,-0.088141,0.865167,297.24,1.077972,45.13,0.827921,NaN,...,6.72,6.77,0,24.426058,1,0,0,1,0,적정
341714,힐티코리아(주)389471,2019,0.013298,0.079086,1.046623,296.69,0.998150,54.34,1.204077,45.4,...,14.52,5.54,0,24.568740,1,0,0,1,0,적정

In [82]:
df_merged1 = df_merged[~(df_merged.년도 == '2009')]

In [83]:
df_merged1

,기업명,년도,매출채권회전율변동,재고자산회전율변동,대손충당금율변동,유동비율,유동비율변동,부채비율,부채비율변동,영업활동현금흐름이자보상비율,...,총종차,매종차,오류수정및회계정책변경여부,자산총계,비상장,상장,상장관리,빅4여부,감사법인변동여부,감사의견
1,(유)건향개발I57907,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,1,0,0,0,0,NaN
2,(유)건향개발I57907,2011,NaN,NaN,NaN,369.56,NaN,36.95,NaN,NaN,...,NaN,NaN,1,19.992317,1,0,0,0,0,NaN
3,(유)건향개발I57907,2012,0.476190,NaN,NaN,204.75,0.554037,73.95,2.001353,NaN,...,NaN,NaN,0,20.482245,1,0,0,0,0,NaN
4,(유)건향개발I57907,2013,NaN,NaN,NaN,378.77,1.849915,31.27,0.422853,NaN,...,9.18,35.37,0,20.385970,1,0,0,0,0,NaN
5,(유)건향개발I57907,2014,NaN,NaN,NaN,419.42,1.107321,34.31,1.097218,NaN,...,194.08,273.49,1,20.443490,1,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341710,힐티코리아(주)389471,2015,0.009321,-0.086831,0.729622,242.31,0.950683,59.56,1.140123,NaN,...,6.13,6.06,0,24.284504,1,0,0,1,0,적정
341711,힐티코리아(주)389471,2016,-0.005277,-0.003170,0.969011,292.61,1.207585,46.20,0.775688,NaN,...,9.26,6.80,0,24.257440,1,0,0,1,0,적정
341712,힐티코리아(주)389471,2017,0.025199,-0.007949,0.812777,275.74,0.942346,54.51,1.179870,NaN,...,0.74,1.49,0,24.394284,1,0,0,1,0,적정
341713,힐티코리아(주)389471,2018,-0.027167,-0.088141,0.865167,297.24,1.077972,45.13,0.827921,NaN,...,6.72,6.77,0,24.426058,1,0,0,1,0,적정
341714,힐티코리아(주)389471,2019,0.013298,0.079086,1.046623,296.69,0.998150,54.34,1.204077,45.4,...,14.52,5.54,0,24.568740,1,0,0,1,0,적정

In [84]:
df_merged1.대손충당금율변동 = df_merged1.대손충당금율변동.replace(np.inf, np.nan)
df_merged1.대손충당금율변동 = df_merged1.대손충당금율변동.replace(-np.inf, np.nan)

df_merged1.자산퀄리티변동 = df_merged1.자산퀄리티변동.replace(np.inf, np.nan)
df_merged1.자산퀄리티변동 = df_merged1.자산퀄리티변동.replace(-np.inf, np.nan)

C:\Users\jo\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [85]:
df = df_merged1.copy()

In [86]:
# 비적정여부 column 추가 

# 주석풀고 실행하면 null있는10개년data.xlsx 파일 생성
# 10개년 + 비적정여부추가(감사의견에서 null, 감사미필 삭제)
# 대손충당금율변동, 자산퀄리티변동 inf, -inf값 처리했음
'''
df_null = df.set_index('감사의견').drop('감사미필').reset_index()
df_null = df_null[~df_null.감사의견.isnull()]
df_null['비적정여부'] = df_null.감사의견.apply(lambda x: 0 if x == '적정' else 1)
df_null.drop('감사의견', axis=1, inplace = True)
df_null = df_null.reset_index()
df_null.pop('index')
df_null.to_excel('null있는10개년data.xlsx')'''

"\ndf_null = df.set_index('감사의견').drop('감사미필').reset_index()\ndf_null = df_null[~df_null.감사의견.isnull()]\ndf_null['비적정여부'] = df_null.감사의견.apply(lambda x: 0 if x == '적정' else 1)\ndf_null.drop('감사의견', axis=1, inplace = True)\ndf_null = df_null.reset_index()\ndf_null.pop('index')\ndf_null.to_excel('null있는10개년data.xlsx')"

In [87]:
df.drop(['적자여부', '오류수정및회계정책변경여부', '비상장', '상장', '상장관리', '빅4여부', '감사법인변동여부', '감사의견'], axis = 1, inplace = True)

In [88]:
df = df.set_index(['기업명','년도'])

In [89]:
df_med = df.groupby(level = 0).median()

In [90]:
df_med

,매출채권회전율변동,재고자산회전율변동,대손충당금율변동,유동비율,유동비율변동,부채비율,부채비율변동,영업활동현금흐름이자보상비율,금융비용_매출액비율,신용평점,...,자산퀄리티변동,감가상각율변동,판관비율,판관비율변동,총발생액비율,총발생액비율변동,매영차,총종차,매종차,자산총계
기업명,,,,,,,,,,,,,,,,,,,,,
(유)건향개발I57907,0.012405,0.722400,NaN,155.670,0.992333,88.270,1.303354,38.640,0.065,4.0,...,0.906579,1.146561,0.050545,0.930637,0.021940,0.307075,3.986929,137.600,35.370,21.440165
(유)그랜드유니버셜트레이딩코리아I83725,0.012846,0.233363,0.891363,73.000,0.924892,984.060,NaN,NaN,NaN,8.0,...,0.000000,1.069467,0.125168,0.894605,NaN,NaN,NaN,NaN,NaN,23.645164
(유)금강주류784532,-0.071190,-0.024750,NaN,52.080,1.046574,423.235,0.870678,24.840,1.315,6.0,...,0.923782,1.021528,0.186290,1.032630,-0.093098,0.091502,0.265513,14.330,12.210,22.270419
(유)기흥모터스113624,-0.053071,0.110536,1.090242,107.990,1.084645,214.110,0.878345,3.995,0.685,5.0,...,0.963579,1.047497,0.241308,0.972255,-0.053108,0.017440,3.539179,11.190,4.780,24.043585
(유)남부상사827894,-0.031664,-0.016331,1.012131,55.055,0.915484,426.550,0.969356,NaN,0.575,6.0,...,0.974807,1.026378,0.125972,0.968558,NaN,NaN,NaN,6.400,16.420,23.722053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
히스보험중개(주)197675,NaN,NaN,NaN,216.005,0.985348,57.710,0.984271,NaN,NaN,3.5,...,0.974889,0.918405,0.837763,1.008989,-0.045876,0.047869,16.108305,17.850,18.095,23.196399
히타치금속한국(주)041866,0.054122,-0.031390,0.957646,208.540,0.993702,60.805,0.984576,17.280,0.425,3.0,...,0.924620,1.017566,0.122284,0.944451,0.008054,-0.003667,7.615242,11.370,15.875,24.367051
히타치하이테크코리아(주)380165,-0.043346,0.080871,0.999999,342.495,0.973074,44.230,0.949614,561.210,0.030,3.0,...,0.819929,0.918703,0.237394,0.907679,-0.007391,0.000375,18.980696,30.645,17.995,24.547873
힐중공업(주)E60148,-0.224601,-0.316692,16.663328,97.065,0.941658,178.470,1.216556,-1.050,1.000,7.0,...,0.666364,0.966055,0.052364,1.310199,0.000672,-0.248584,7.631141,56.005,48.335,22.215352
힐티코리아(주)389471,0.046892,-0.005559,0.885454,265.310,1.038061,54.425,0.928473,45.400,0.180,4.0,...,0.951586,0.998763,0.281186,0.963329,0.045834,-0.011463,3.783611,8.770,6.785,24.188204

In [91]:
df

                     매출채권회전율변동  재고자산회전율변동  대손충당금율변동    유동비율    유동비율변동   부채비율  \
기업명            년도
(유)건향개발I57907  2010        NaN        NaN       NaN     NaN       NaN    NaN
               2011        NaN        NaN       NaN  369.56       NaN  36.95
               2012   0.476190        NaN       NaN  204.75  0.554037  73.95
               2013        NaN        NaN       NaN  378.77  1.849915  31.27
               2014        NaN        NaN       NaN  419.42  1.107321  34.31
...                        ...        ...       ...     ...       ...    ...
힐티코리아(주)389471 2015   0.009321  -0.086831  0.729622  242.31  0.950683  59.56
               2016  -0.005277  -0.003170  0.969011  292.61  1.207585  46.20
               2017   0.025199  -0.007949  0.812777  275.74  0.942346  54.51
               2018  -0.027167  -0.088141  0.865167  297.24  1.077972  45.13
               2019   0.013298   0.079086  1.046623  296.69  0.998150  54.34

                       부채비율변동  영업활동현금흐름이자보상비율  금융비용_매출액비율  신용평점  ...  \
기업명            년도                                                ...
(유)건향개발I57907  2010       NaN             NaN         NaN   NaN  ...
               2011       NaN             NaN        0.03   4.0  ...
               2012  2.001353             NaN        0.05   4.0  ...
               2013  0.422853             NaN        0.04   4.0  ...
               2014  1.097218             NaN        0.35   4.0  ...
...                       ...             ...         ...   ...  ...
힐티코리아(주)389471 2015  1.140123             NaN         NaN   4.0  ...
               2016  0.775688             NaN         NaN   4.0  ...
               2017  1.179870             NaN         NaN   5.0  ...
               2018  0.827921             NaN         NaN   3.0  ...
               2019  1.204077            45.4        0.18   3.0  ...

                      자산퀄리티변동   감가상각율변동      판관비율    판관비율변동    총발생액비율  \
기업명            년도
(유)건향개발I57907  2010       NaN       NaN       NaN       NaN       NaN
               2011       NaN       NaN  0.081577       NaN       NaN
               2012       NaN       NaN  0.086784  1.063832       NaN
               2013       NaN       NaN  0.061535  0.709054       NaN
               2014  0.914065  2.515607  0.400644  6.510866       NaN
...                       ...       ...       ...       ...       ...
힐티코리아(주)389471 2015  0.869577  1.566230  0.247722  0.788437  0.027315
               2016  1.056277  0.942432  0.252610  1.019731  0.085114
               2017  0.398421  0.702132  0.249744  0.988654  0.098372
               2018  1.382511  1.076242  0.283610  1.135605  0.007221
               2019  0.695364  0.549383  0.321642  1.134098 -0.098288

                     총발생액비율변동       매영차     총종차     매종차       자산총계
기업명            년도
(유)건향개발I57907  2010       NaN       NaN     NaN     NaN        NaN
               2011       NaN       NaN     NaN     NaN  19.992317
               2012       NaN       NaN     NaN     NaN  20.482245
               2013       NaN       NaN    9.18   35.37  20.385970
               2014       NaN       NaN  194.08  273.49  20.443490
...                       ...       ...     ...     ...        ...
힐티코리아(주)389471 2015 -0.009391  4.181857    6.13    6.06  24.284504
               2016  0.057050  2.789865    9.26    6.80  24.257440
               2017  0.024143  2.610911    0.74    1.49  24.394284
               2018 -0.088074  3.820559    6.72    6.77  24.426058
               2019 -0.104548  3.746663   14.52    5.54  24.568740

[310650 rows x 26 columns]

In [92]:
기업_리스트 = df_med.index

In [93]:
att_리스트 = df_med.columns

In [94]:
for i in 기업_리스트:
    for j in att_리스트:
        df.loc[i][j].fillna(df_med.loc[i][j],inplace=True)

In [95]:
df_med_in_nan = df.reset_index()

In [96]:
df_med_in_nan = pd.merge(df_med_in_nan, df_merged1[['기업명','년도','적자여부', '오류수정및회계정책변경여부', '비상장', '상장', '상장관리', '빅4여부', '감사법인변동여부', '감사의견']])

In [97]:
df_med_in_nan # 10개년 원본데이터에 median값으로 채운것 10년이 다 null이면 계속 null이다. null 다 제거하고 돌려보고 채워서도 돌려보고

,기업명,년도,매출채권회전율변동,재고자산회전율변동,대손충당금율변동,유동비율,유동비율변동,부채비율,부채비율변동,영업활동현금흐름이자보상비율,...,매종차,자산총계,적자여부,오류수정및회계정책변경여부,비상장,상장,상장관리,빅4여부,감사법인변동여부,감사의견
0,(유)건향개발I57907,2010,0.012405,0.722400,NaN,155.67,0.992333,88.27,1.303354,38.64,...,35.37,21.440165,1,0,1,0,0,0,0,NaN
1,(유)건향개발I57907,2011,0.012405,0.722400,NaN,369.56,0.992333,36.95,1.303354,38.64,...,35.37,19.992317,1,1,1,0,0,0,0,NaN
2,(유)건향개발I57907,2012,0.476190,0.722400,NaN,204.75,0.554037,73.95,2.001353,38.64,...,35.37,20.482245,1,0,1,0,0,0,0,NaN
3,(유)건향개발I57907,2013,0.012405,0.722400,NaN,378.77,1.849915,31.27,0.422853,38.64,...,35.37,20.385970,1,0,1,0,0,0,0,NaN
4,(유)건향개발I57907,2014,0.012405,0.722400,NaN,419.42,1.107321,34.31,1.097218,38.64,...,273.49,20.443490,1,1,1,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310645,힐티코리아(주)389471,2015,0.009321,-0.086831,0.729622,242.31,0.950683,59.56,1.140123,45.40,...,6.06,24.284504,0,0,1,0,0,1,0,적정
310646,힐티코리아(주)389471,2016,-0.005277,-0.003170,0.969011,292.61,1.207585,46.20,0.775688,45.40,...,6.80,24.257440,0,0,1,0,0,1,0,적정
310647,힐티코리아(주)389471,2017,0.025199,-0.007949,0.812777,275.74,0.942346,54.51,1.179870,45.40,...,1.49,24.394284,0,0,1,0,0,1,0,적정
310648,힐티코리아(주)389471,2018,-0.027167,-0.088141,0.865167,297.24,1.077972,45.13,0.827921,45.40,...,6.77,24.426058,0,0,1,0,0,1,0,적정
310649,힐티코리아(주)389471,2019,0.013298,0.079086,1.046623,296.69,0.998150,54.34,1.204077,45.40,...,5.54,24.568740,0,0,1,0,0,1,0,적정

In [98]:
# 비적정여부 column 추가

df_new = df_med_in_nan.set_index('감사의견').drop('감사미필').reset_index()
df_new = df_new[~df_new.감사의견.isnull()]
df_new['비적정여부'] = df_new.감사의견.apply(lambda x: 0 if x == '적정' else 1)
df_new.drop('감사의견', axis=1, inplace = True)

In [99]:
df_new = df_new.reset_index()

In [100]:
df_new.pop('index')

0              8
1              9
2             28
3             29
4             30
           ...
193204    295580
193205    295581
193206    295582
193207    295583
193208    295584
Name: index, Length: 193209, dtype: int64

In [107]:
df_new

,기업명,년도,매출채권회전율변동,재고자산회전율변동,대손충당금율변동,유동비율,유동비율변동,부채비율,부채비율변동,영업활동현금흐름이자보상비율,...,매종차,자산총계,적자여부,오류수정및회계정책변경여부,비상장,상장,상장관리,빅4여부,감사법인변동여부,비적정여부
0,(유)건향개발I57907,2018,-0.706949,2.679380,NaN,110.07,0.718051,391.98,2.635691,84.83,...,16.66,23.759990,0,0,1,0,0,0,1,1
1,(유)건향개발I57907,2019,-0.469072,1.632373,NaN,128.86,1.170710,197.85,0.504745,-7.55,...,5.38,23.878219,0,0,1,0,0,0,0,0
2,(유)금강주류784532,2019,-0.227564,-0.096682,NaN,87.21,1.015368,3128.15,0.046595,18.28,...,12.21,23.484770,0,0,1,0,0,0,1,0
3,(유)기흥모터스113624,2010,0.158547,-0.005780,0.896905,64.23,1.039657,709.17,0.876168,3.99,...,4.48,23.856282,0,0,1,0,0,0,0,0
4,(유)기흥모터스113624,2011,-0.167466,0.162791,0.688436,74.69,1.162852,597.47,0.842492,4.00,...,4.78,23.900213,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193204,힐티코리아(주)389471,2015,0.009321,-0.086831,0.729622,242.31,0.950683,59.56,1.140123,45.40,...,6.06,24.284504,0,0,1,0,0,1,0,0
193205,힐티코리아(주)389471,2016,-0.005277,-0.003170,0.969011,292.61,1.207585,46.20,0.775688,45.40,...,6.80,24.257440,0,0,1,0,0,1,0,0
193206,힐티코리아(주)389471,2017,0.025199,-0.007949,0.812777,275.74,0.942346,54.51,1.179870,45.40,...,1.49,24.394284,0,0,1,0,0,1,0,0
193207,힐티코리아(주)389471,2018,-0.027167,-0.088141,0.865167,297.24,1.077972,45.13,0.827921,45.40,...,6.77,24.426058,0,0,1,0,0,1,0,0
193208,힐티코리아(주)389471,2019,0.013298,0.079086,1.046623,296.69,0.998150,54.34,1.204077,45.40,...,5.54,24.568740,0,0,1,0,0,1,0,0

In [108]:
# 주석풀고 실행하면 median채운10개년.xlsx 파일 생성
# median으로 null값 채울수 있는부분은 채움
# 10개년 + 비적정여부추가(감사의견에서 null, 감사미필 삭제)
# 대손충당금율변동, 자산퀄리티변동 inf, -inf값 처리했음


#df_new.to_excel('median채운10개년.xlsx')

In [102]:
data = df_new.copy()

In [103]:
data.columns

Index(['기업명', '년도', '매출채권회전율변동', '재고자산회전율변동', '대손충당금율변동', '유동비율', '유동비율변동',
       '부채비율', '부채비율변동', '영업활동현금흐름이자보상비율', '금융비용_매출액비율', '신용평점', '자기자본순이익률',
       '자기자본순이익률변동', 'ROA', 'ROA변동', '매출액증가율', '자산퀄리티', '자산퀄리티변동', '감가상각율변동',
       '판관비율', '판관비율변동', '총발생액비율', '총발생액비율변동', '매영차', '총종차', '매종차', '자산총계',
       '적자여부', '오류수정및회계정책변경여부', '비상장', '상장', '상장관리', '빅4여부', '감사법인변동여부',
       '비적정여부'],
      dtype='object')

In [104]:
data.매출채권회전율변동 = data.매출채권회전율변동.fillna(0)
data.재고자산회전율변동 = data.재고자산회전율변동.fillna(0)
data.대손충당금율변동 = data.대손충당금율변동.fillna(1)
data = data[~data.유동비율.isnull()]
data.유동비율변동 = data.유동비율변동.fillna(1)
data.부채비율변동 = data.부채비율변동.fillna(1)
data = data[~data.신용평점.isnull()]
data.자기자본순이익률변동 = data.자기자본순이익률변동.fillna(1)
data.ROA변동 = data.ROA변동.fillna(1)
data.자산퀄리티변동 = data.자산퀄리티변동.fillna(1)
data.감가상각율변동 = data.감가상각율변동.fillna(1)
data.판관비율변동 = data.판관비율변동.fillna(1)
data.총발생액비율변동 = data.총발생액비율변동.fillna(1)
data.매영차 = data.매영차.fillna(0)
data.매종차 = data.매종차.fillna(0)
data.총종차 = data.총종차.fillna(0)

In [109]:
data

,기업명,년도,매출채권회전율변동,재고자산회전율변동,대손충당금율변동,유동비율,유동비율변동,부채비율,부채비율변동,영업활동현금흐름이자보상비율,...,매종차,자산총계,적자여부,오류수정및회계정책변경여부,비상장,상장,상장관리,빅4여부,감사법인변동여부,비적정여부
0,(유)건향개발I57907,2018,-0.706949,2.679380,1.000000,110.07,0.718051,391.98,2.635691,84.83,...,16.66,23.759990,0,0,1,0,0,0,1,1
1,(유)건향개발I57907,2019,-0.469072,1.632373,1.000000,128.86,1.170710,197.85,0.504745,-7.55,...,5.38,23.878219,0,0,1,0,0,0,0,0
2,(유)금강주류784532,2019,-0.227564,-0.096682,1.000000,87.21,1.015368,3128.15,0.046595,18.28,...,12.21,23.484770,0,0,1,0,0,0,1,0
3,(유)기흥모터스113624,2010,0.158547,-0.005780,0.896905,64.23,1.039657,709.17,0.876168,3.99,...,4.48,23.856282,0,0,1,0,0,0,0,0
4,(유)기흥모터스113624,2011,-0.167466,0.162791,0.688436,74.69,1.162852,597.47,0.842492,4.00,...,4.78,23.900213,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193204,힐티코리아(주)389471,2015,0.009321,-0.086831,0.729622,242.31,0.950683,59.56,1.140123,45.40,...,6.06,24.284504,0,0,1,0,0,1,0,0
193205,힐티코리아(주)389471,2016,-0.005277,-0.003170,0.969011,292.61,1.207585,46.20,0.775688,45.40,...,6.80,24.257440,0,0,1,0,0,1,0,0
193206,힐티코리아(주)389471,2017,0.025199,-0.007949,0.812777,275.74,0.942346,54.51,1.179870,45.40,...,1.49,24.394284,0,0,1,0,0,1,0,0
193207,힐티코리아(주)389471,2018,-0.027167,-0.088141,0.865167,297.24,1.077972,45.13,0.827921,45.40,...,6.77,24.426058,0,0,1,0,0,1,0,0
193208,힐티코리아(주)389471,2019,0.013298,0.079086,1.046623,296.69,0.998150,54.34,1.204077,45.40,...,5.54,24.568740,0,0,1,0,0,1,0,0

In [110]:
# 주석풀고 실행하면 'attribute_raw.xlsx' 파일 생성
# median으로 null값 채울수 있는부분은 채움
# 10개년 + 비적정여부추가(감사의견에서 null, 감사미필 삭제)
# 대손충당금율변동, 자산퀄리티변동 inf, -inf값 처리했음
# 비율,변동 0,1로 채울수 있는부분채움


#data = data.reset_index()
#data.pop('index')
#data.to_excel('attribute_raw.xlsx')